env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "x64"
    binary: solt
    ldflags: -s -w -X solt/cmd.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

  - id: "386"
    binary: solt
    ldflags: -s -w -X solt/cmd.Version={{ .Version }}
    goos:
      - linux
      - windows
    goarch:
      - 386

  - id: "arm"
    binary: solt
    ldflags: -s -w -X solt/cmd.Version={{ .Version }}
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7

  - id: "arm64"
    binary: solt
    ldflags: -s -w -X solt/cmd.Version={{ .Version }}
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - id: default
    builds:
      - x64
      - arm
      - arm64
      - 386

brews:
-
    goarm: 7
    tap:
      owner: aegoroff
      name: homebrew-tap
    commit_author:
      name: "Alexander Egorov"
      email: "egoroff@gmail.com"
    test: |
      assert_match version.to_s, shell_output("#{bin}/solt ver")
    homepage: "https://github.com/aegoroff/solt"
    description: "Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects"
    license: "MIT"

scoop:
  bucket:
    owner: aegoroff
    name: scoop-bucket
  homepage:  https://github.com/aegoroff/solt
  description: Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects
  license: MIT

nfpms:
  -
    package_name: solt
    homepage: https://github.com/aegoroff/solt
    maintainer: Alexander Egorov <egoroff@gmail.com>
    description: Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects
    license: MIT
    bindir: /usr/bin
    formats:
      - deb
      - rpm

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"

