# version format
version: 0.1.{build}

clone_folder: c:\gopath\src\solt

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\usr\bin;%PATH%
  - go version
  - go env
  - go get -u "github.com/anknown/ahocorasick"
  - go get -u "github.com/dustin/go-humanize"
  - go get -u "github.com/voxelbrain/goptions"
  - go get -u "github.com/stretchr/testify/assert"
  - go get -u "github.com/aegoroff/godatastruct/rbtree"
  - go get -u "github.com/akutz/sortfold"
  - go get -u "gonum.org/v1/gonum/graph/simple"

stack: go 1.11

image: Visual Studio 2017

build_script:
  - go build -ldflags "-X main.Version=%APPVEYOR_BUILD_VERSION%" solt

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic solt/...

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.txt" -t $env:CODECOV_TOKEN

artifacts:
  - path: solt.exe
    name: binary

