# version format
version: 0.9.1.{build}

clone_folder: c:\gopath\src\solt

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\usr\bin;%PATH%
  - go version
  - go env

stack: go ^1.15

image: Visual Studio 2019

build_script:
  - go build -ldflags "-s -w -X solt/cmd.Version=%APPVEYOR_BUILD_VERSION%" solt

test_script:
  - go test -coverprofile=coverage.txt -coverpkg solt/internal/sys,solt/msvc,solt/cmd,solt/solution -covermode=atomic solt/...

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      ./codecov.sh -f "coverage.txt" -t $env:CODECOV_TOKEN

artifacts:
  - path: solt.exe
    name: binary

